### PR TITLE
DROOLS-5496: Remove drools-compiler duplicates

### PR DESCRIPTION
**Pull request by jomarko**
This PR removes duplicates present also in https://github.com/kiegroup/drools/tree/master/drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers
For more details see: https://issues.redhat.com/browse/DROOLS-5496

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
@mbiarnes hello, may I ask you for help with running FDB here? Not sure if this repository has some exceptional rules/triggers. Not working with it too often.

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
this is leaf repository. so we don't need to run FDB here IMHO

**Comment by mbiarnes** [comment]
Jenkins run full downstream build

**Comment by jomarko** [comment]
Failed tests:
```
org.kie.hacep.KafkaTest.basicTest
org.kie.hacep.KafkaTest.testKafkaLoggerWithStringTest
org.kie.hacep.PodAsLeaderSnapshotTest.processMessagesAsLeaderAndCreateSnapshotTest
org.kie.hacep.PodAsLeaderTest.processOneSentMessageAsLeaderTest
org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
org.kie.hacep.RemoteKieSessionImplTest.getFactCountTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithClassTypeTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getFactCountTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest
org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsWithNamedQueryTest
org.kie.hacep.SnapshotOnDemandTest.createSnapshotOnDemandTest
org.kie.hacep.core.infra.SnapshotOnDemandUtilsTest.askAKafkaConsumerWithoutServerUpTest
org.kie.hacep.core.infra.SnapshotOnDemandUtilsTest.askASnapshotWithoutServerUpTest
org.kie.hacep.core.infra.utils.ConsumerUtilsCoreTest.lastEventWithoutKafkaUpTest
org.kie.spring.tests.persistence.VariablePersistenceStrategyEnvTest.testPersistenceVariables
org.kie.spring.tests.persistence.VariablePersistenceStrategyEnvTest.testTransactionsRollback
```

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by mareknovotny** [comment]
@rsynek there is not setup FDB on this repository just to be crystal clear, we had only CDB for drools PRs in past, now probably when @mbiarnes applied new PR,CDB jobs it was lost

**Comment by rsynek** [comment]
@mareknovotny I've already replied on the chat. Please ignore my request for the FDB - I didn't realize it was meaningless in this repository when @jomarko tried to trigger it.

**Pull request merged**
