### PR TITLE
DROOLS-2342: Update Kie Navigator to the new git/rest structure

### PR DESCRIPTION
**Pull request by tiagobento**
See: https://issues.jboss.org/browse/DROOLS-2342

Here's a quick video demo: https://youtu.be/6KQb2AlWz3M

The errors you see at 4:17 and 5:50 seem to already be fixed on the Workbench and are not related with this PR.

### CODE REVIEW

**Comment by tiagobento** [comment]
@krisv Could you please take a look?

**Comment by tiagobento** [comment]
@krisv Absolutely. Since we're fixing breaking changes that happened from 7.6 to 7.7, maybe it's better to call it Kie770Service/jbpm770? Wdyt?

**Comment by tomasdavidorg** [comment]
Thanks :-). @tiagobento two remarks:
- We are mixing spaces and tabs. Not sure if there is some codestyle for this project but it looks like all the project sources use tabs. I think it is better if we stay with them.
- For discussion: The Spaces are still named as Org. units in this project. Same for repositories but the they are repositories even if they contain only one project and in this level of abstraction it makes sense because the tooling is used by more advanced users. In case of Org. units we should consider to rename to "Spaces".

**Comment by tiagobento** [comment]
Hi @tomasdavidorg! 

I'm using the kie-group formatter since this project is under the kiegroup organization. I tried to keep the formatting changes at a minimum but there were files I didn't bother changing because it's visible that it's only spaces/tabs mixing up. I think we should consider formatting the whole project at once after this PR is merged.

About `Organization Units` being renamed to `Spaces`, that was something I discussed with @krisv and we settled for no renaming. If something changed since, I'm OK with renaming it now :)

**Comment by jhrcek** [comment]
@tiagobento +1 to whole project formatting in separate PR

**Comment by krisv** [comment]
@tiagobento I think the idea of keeping org. units was when we were considering to also keep it backwards compatible.  Since this only works for v7.7+ I think just renaming org. units to spaces would make sense.

**Comment by tiagobento** [comment]
@krisv Renamed on 12db502.

**Comment by tiagobento** [comment]
@krisv Do you think we should merge this PR or close it and open another one with the backward-compatible feature?

**Pull request merged**
