### PR TITLE
disabled drools-eclipse module

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by triceo** [comment]
6.3.x? Am I missing something?

**Comment by psiroky** [comment]
We still build the old branches like once a week to make sure they are buildable in case of one-offs.

**Comment by psiroky** [comment]
@mbiarnes the only thing the `distribution` module does is that it packages the `drools-eclipse` module, so we need to disable that as well.

**Comment by mbiarnes** [comment]
@psiroky will do so

**Comment by mbiarnes** [comment]
@psiroky like discussed I will close this PR and raise another one which removes this rep from the repository-list.txt

**Pull request closed without merging**
