### PR TITLE
JBRULES-3236 : Add completion support for ruleflow-group name

### PR DESCRIPTION
**Pull request by jerr**

### CODE REVIEW

**Comment by bbrodt** [comment]
Thanks Jérémie, but I was just made aware of this PR and I'm afraid we can't risk merging it at this time because we are already behind schedule for the 6.2.0 product release. I will look at this again after the release.

**Comment by psiroky** [comment]
@bbrodt so could we merge this (and possible the other PRs) into master?

**Comment by psiroky** [comment]
Note that the PR is 4 years old and it does not merge cleanly right now.

**Comment by bbrodt** [comment]
Sure, right after the 6.2.0 product release.

On Fri, Oct 16, 2015 at 1:04 PM, Petr Široký <notifications@github.com>
wrote:

> Note that the PR is 4 years old and it does not merge cleanly right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/droolsjbpm/droolsjbpm-tools/pull/4#issuecomment-148808120>
> .
>



-- 
________________________
Robert ("Bob") Brodt
Senior Software Engineer
JBoss by Red Hat

**Pull request closed without merging**
