### PR TITLE
[JBPM-8380] Remove JBPMHelper

### PR DESCRIPTION
**Pull request by karlnicholas**
Updates to be pulled in tandem with https://github.com/kiegroup/jbpm/pull/1477

### CODE REVIEW

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by MarianMacik** [comment]
ok to test

**Comment by mswiderski** [comment]
@MarianMacik @elguardian guys, could you please review and approve so it can be merged?

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by krisv** [comment]
@mswiderski @MarianMacik did we check if this code still works with jBPM 6.0 and above?  As we reuse this file for all versions (v5 has its own version).

**Comment by mswiderski** [comment]
I haven't tried it so not sure but what you wrote kind of scares me ... isn't that a bit of too much of code reuse

**Comment by karlnicholas** [comment]
@krisv - which code are you referring to?

**Comment by MarianMacik** [comment]
This was only done on master, so I believe it should be OK for other versions.

**Pull request merged**
